name: petgo_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  lottie: ^2.3.2
  smooth_page_indicator: ^1.1.0
  flutter_lints: ^5.0.0
  country_code_picker: ^3.3.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  introduction_screen: ^3.1.17
  pin_code_fields: ^8.0.0
  lucide_icons: ^0.257.0
  dropdown_button2: ^2.3.9
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  location: ^8.0.0
  get: ^4.7.2
  provider : ^6.0.0
  url_launcher: ^6.2.4
  moyasar: ^2.0.16
  timeline_tile: ^2.0.0
  timelines_plus: ^1.0.7
  font_awesome_flutter: ^10.7.0



flutter:
  uses-material-design: true
  assets:

    - assets/app_img/
    - assets/icons/
    - assets/logo/
dev_dependencies:
  flutter_test:
    sdk: flutter


